# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: 'style: auto fixes from pre-commit.ci hooks'
  autofix_prs: false
  autoupdate_commit_msg: 'chore(deps): pre-commit.ci autoupdate'
  autoupdate_schedule: monthly
exclude: ^(3rdpart|cmake/ECM|cmake/KDAB/|src/3rdparty/|code.dev.code-workspace)
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
        exclude: ^(\.devcontainer/devcontainer.json|\.vscode/)
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-vcs-permalinks
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: (.+/snapshots/.+)|(.*docs/_freeze/.+\.json)|(.+\.excalidraw)
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
        exclude: .+/snapshots/.+

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        entry: mdl
        language: ruby
        files: \.(md|mdown|markdown)$
        exclude: \.github/

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies: [mdformat-gfm, mdformat-frontmatter, mdformat-footnote]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'
    hooks:
      - id: prettier
        types_or: [yaml, html, json]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ['-L', 'sur,nd']

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 'v1.10.0'
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: '1.7.0'
    hooks:
      - id: pyproject-fmt
        # https://pyproject-fmt.readthedocs.io/en/latest/#calculating-max-supported-python-version
        additional_dependencies: ['tox>=4.9']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        types_or: [python, jupyter]
        args: ['--fix', '--show-fixes']
      - id: ruff-format
        types_or: [python, jupyter]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.27
    hooks:
      - id: actionlint-system

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        types_or:
          - sh
          - shell
          - ash
          - bash
          - bats
          - dash
          - ksh

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/fsfe/reuse-tool
    rev: v3.0.1
    hooks:
      - id: reuse
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: system
        entry: prettier
        args: ['--write']
        types_or:
          - javascript
          - json
          - markdown
          - yaml
      - id: shfmt
        name: shfmt
        language: system
        entry: shfmt
        args: ['-i', '2', '-sr', '-s']
        types_or:
          - sh
          - shell
          - ash
          - bash
          - bats
          - dash
          - ksh
