site_name: TEST-CONNECTIONS
site_description: A tester for differt hosts for available.
site_url: https://io.github.org/jmuelbert/test-connections/

theme:
  name: 'material'
  features:
    - navigation.sections

repo_name: jmuelbert/test-connections
repo_url: https://github.com/jmuelbert/test-connections/
edit_uri: ''

nav:
  - Introduction: 'index.md'
  - Usage:
      - QuickStart: 'quickstart.md'
      - Advanced Usage: 'advanced.md'
  - Guides:
      - Async Support: 'async.md'
      - HTTP/2 Support: 'http2.md'
      - Requests Compatibility: 'compatibility.md'
      - Troubleshooting: 'troubleshooting.md'
  - API Reference:
      - Developer Interface: 'api.md'
      - Exceptions: 'exceptions.md'
      - Environment Variables: 'environment_variables.md'
  - Community:
      - Third Party Packages: 'third_party_packages.md'
      - Contributing: 'contributing.md'
      - Code of Conduct: 'code_of_conduct.md'

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: ''
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {
              kwds: {mode: generic, tag: pre},
            }
        - name: md-render
          class: md-render
          format: !!python/name:tools.pymdownx_md_render.md_sub_render
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {
              kwds: {mode: generic},
            }
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path:
        - docs/src/markdown/.snippets
        - LICENSE.md
      auto_append:
        - refs.md
      check_paths: true
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.saneheaders:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/facelessuser
    - icon: fontawesome/brands/discord
      link: https://discord.gg/TWs8Tgr
extra_css:
  # - https://cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.css
  - assets/pymdownx-extras/extra.css
extra_javascript:
  - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  # - https://cdn.jsdelivr.net/npm/katex@0.13.18/dist/katex.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader.js

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
