# Project information
site_name: test-connections
site_description: Checker for URL's and NTP-Servere
site_author: Jürgen Mülbert
site_url: https://io.github.com/jmuelbert/test-connections
docs_dir: docs/linkified

# Repository
repo_name: jmuelbert/test-connections
repo_url: https://github.com/jmuelbert/test-connections
edit_uri: ""
nav:
  - Introduction: index.md
  - CLI: cli.md  

# Copyright
copyright: Copyright &copy; 2023 - 2024

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Fira Sans
    code: Fira Code
  logo: img/icon.png
  favicon: img/favicon.ico
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.prune

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jmuelbert/test-connections
  version:
    provider: mike

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - mdx_include
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      watch: [launch]
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            heading_level: 2
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: 'docs.plugins:on_pre_build'
        on_files: 'docs.plugins:on_files'
        on_page_markdown: 'docs.plugins:on_page_markdown'

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

extra_css:
  - stylesheets/extra.css