[tool.poetry]
name = "test-connections"
version = "0.1.0"
description = ""
authors = ["Jürgen Mülbert <juergen.muelbert@outlook.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
