name: Release documentation

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, develop, release]
    paths:
      - docs/**
      - mkdocs.yml
      - pyproject.toml
      - .github/workflows/docs-release.yml

  pull_request:
    types: [closed]

jobs:
  release-docs:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the docs release event
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: release-docs
          client-payload: >
            {
              "tag": "${{ github.ref_name }}"
            }
