name: pre-commit

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, develop, release, Update-GitHub-Actions]

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: "🧰 Checkout Source Code"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "🐍 Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.x

      - name: "Perform Pre-Commit"
        uses: pre-commit/action@v3.0.0
