---
# SPDX-FileCopyrightText: Dr. Jan-Philip Gehrcke
#
# SPDX-License-Identifier: Apache-2.0
#

name: github-repo-stats

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@306db38ad131cab2aa5f2cd3062bf6f8aa78c1aa # V 1.4.2
        with:
          ghtoken: ${{ secrets.ghrs_github_api_token }}
